### ISSUE TITLE
Double dash for argument prefix

### ISSUE THREAD

**Issue by dmarlow** [SvenGroot/ookii.commandline#5] opened 2020-03-12 20:03 UTC
I'm specifying the argument prefix like this: 
`var parser = new CommandLineParser(typeof(Options), new[] { "-", "--" });`

But, when I attempt to use `--` like this:
`myapp.exe --flag`

I get the following error:
`Unknown argument name '-flag'.`

Looks like if I switch the order of the prefixes, it works. 🤷‍♂

**Comment by SvenGroot** [comment] 2022-09-01 19:07
This is working as intended. The prefixes are checked in the order they are provided, so when `-` matches, `--` is never considered. As you indicated, the solution is to specify the longer prefixes first.

**Closed by SvenGroot** 2022-09-01 19:07 UTC
